version: '3.7'  
services:  
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kzakharov/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - /home/ec2-user/openvpn_new:/etc/openvpn
